version: "3.9"
services:
  nginx:
    container_name: nginx
    image: nginx
    volumes:
      - ./etc/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./etc/nginx/fastcgi.conf:/etc/nginx/fastcgi.conf
      - ./etc/nginx/mime.types:/etc/nginx/mime.types
      - .:/app
    ports:
      - "8080:80"
  php-fpm:
    container_name: php-fpm
    build:
      context: .
      dockerfile: Dockerfile.php-fpm
    volumes:
      - .:/app
    ports:
      - "9000:9000"
  mysql:
    container_name: mysql
    image: mysql
    environment:
      MYSQL_DATABASE: example
      MYSQL_USER: my_user
      MYSQL_PASSWORD: my_password
      MYSQL_ROOT_PASSWORD: my_root_password
    ports:
      - "3306:3306"
