version: "3.9"
services:
  nginx:
    container_name: nginx
    image: nginx
    volumes:
      - ./etc/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./etc/nginx/fastcgi.conf:/etc/nginx/fastcgi.conf
      - ./etc/nginx/mime.types:/etc/nginx/mime.types
      - .:/app
    ports:
      - "8080:80"
  php-fpm:
    container_name: php-fpm
    image: php:8.0-fpm-bullseye
    volumes:
      - .:/app
    ports:
      - "9000:9000"
